name: Build
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    paths:
    - ".github/workflows/build.yaml"
    - "src/**/*"
  pull_request:
    paths:
    - "src/**/*"

env:
  SDCC_VERSION: 4.2.0

jobs:
  Build_Windows:
    runs-on: windows-latest
    steps:
    - name: install SDCC
      run: | #install silent and then unpack missing installation libraries
        Invoke-WebRequest https://altushost-swe.dl.sourceforge.net/project/sdcc/sdcc-win64/$env:SDCC_VERSION/sdcc-$env:SDCC_VERSION-x64-setup.exe -OutFile sdcc_setup.exe
        Start-Process -wait -FilePath "sdcc_setup.exe" -ArgumentList "/S", "/D=C:\Program Files\SDCC"
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd src/controller
        ./compile.bat
    - uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: bin/main.ihx


  Build_Linux:
    runs-on: ubuntu-22.04
    steps:
      - name: install SDCC
        run: |
           cd ~
           wget https://altushost-swe.dl.sourceforge.net/project/sdcc/sdcc-linux-amd64/$SDCC_VERSION/sdcc-$SDCC_VERSION-amd64-unknown-linux2.5.tar.bz2
           sudo tar xf sdcc-$SDCC_VERSION-amd64-unknown-linux2.5.tar.bz2
           cd sdcc-$SDCC_VERSION/
           sudo cp -r * /usr/local
           sdcc --version
           sdcc --print-search-dirs
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd src/controller
          make clean
          make
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: bin/main.ihx
